# Generated by Django 4.2.5 on 2023-09-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
