# Generated by Django 4.2.5 on 2023-09-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auth',
            new_name='author',
        ),
    ]
